[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
counter_workshop = "DfhyXbqLN1DCWLNBnHxLxnBgN5vQpRMnQBZW1Dvmthp1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ascespool/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
